package com.nyth.app.core.model.local.enums

enum class InputType {
    TEXT,
    EMAIL,
    PHONE,
    NUMBER,
    ACTIVITY_NAME,
    LISTING_NAME,
    LISTING_PRICE,
    LISTING_CONTACT_ISSUE_TITLE,
    LISTING_CONTACT_NAME,
    LISTING_CONTACT_SURNAME,
    LISTING_CONTACT_ISSUE_DESCRIPTION,
    ACCOUNT_FIRST_NAME,
    ACCOUNT_LAST_NAME,
    ACCOUNT_USER_NAME,
    CARD_NAME,
    CARD_NUMBER,
    CARD_EXPIRATION_DATE,
    CARD_CVC,
}
